basePath: /api/ocloudNotifications/v2
externalDocs:
  description: PTP Events REST API V2 Reference
  url: https://docs.openshift.com/container-platform/4.17/networking/ptp/ptp-events-rest-api-reference-v2.html
host: localhost:8089
info:
  contact:
    email: ptp-dev@redhat.com
    name: PTP Dev Team
  description: This is an implementation of O-Cloud Notification API specification
    for Event Consumers v04.00
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: O-RAN Compliant REST-API
  version: "1.0"
paths: {}
swagger: "2.0"
