basePath: /api/ocloudNotifications/v2
host: localhost:8089
info:
  contact:
    email: ptp-dev@redhat.com
    name: PTP Dev Team
  description: This is an implementation of O-Cloud Notification API specification
    for Event Consumers v04.00
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: O-RAN compliant REST-API
  version: "1.0"
paths: {}
swagger: "2.0"
